[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "always"

[[services]]
name = "leave-management-frontend"
source = "."

[services.variables]
NEXT_PUBLIC_API_URL = "${{BACKEND_URL}}/api/v1"
NODE_ENV = "production"