[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run dev"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "leave-management-frontend"
source = "./frontend"

[services.variables]
NEXT_PUBLIC_API_URL = "${{BACKEND_URL}}/api/v1"
NODE_ENV = "production"
