[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "leave-management-backend"
source = "."

[services.variables]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
FRONTEND_URL = "${{FRONTEND_URL}}"
ENVIRONMENT = "production"
